# use alt+tab/alt+maj+tab to move between windows
bind -n M-Tab next-window
bind -n M-BTab previous-window

# ctrl+alt+left/right or h/l to move between sessions
bind -n C-M-Left switch-client -p
bind -n C-M-Right switch-client -n
bind -n C-M-h switch-client -p
bind -n C-M-l switch-client -n

# ctrl+alt+j/k to move between windows
bind -n C-M-j next-window
bind -n C-M-k previous-window

# pane navigation - @is_vim set by nvim autocmds
bind-key -n C-h if-shell -F '#{==:#{@is_vim},on}' "send-keys C-h" "select-pane -L"
bind-key -n C-j if-shell -F '#{==:#{@is_vim},on}' "send-keys C-j" "select-pane -D"
bind-key -n C-k if-shell -F '#{==:#{@is_vim},on}' "send-keys C-k" "select-pane -U"
bind-key -n C-l if-shell -F '#{==:#{@is_vim},on}' "send-keys C-l" "select-pane -R"
bind-key -n C-v copy-mode
bind-key -n C-p paste-buffer

bind ù split-window -v -c "#{pane_current_path}" # split pane <prefix>" now bound to <prefix>ù
bind % split-window -h -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"
bind x confirm-before -p "kill-window #W? (y/n)" kill-window
bind X confirm-before -p "kill-session #S? (y/n)" kill-session
bind g display-popup -E -w 80% -h 80% -d "#{pane_current_path}" "$SHELL"
bind C command-prompt -p "new session:" "new-session -s '%%'"
bind m command-prompt -p "move pane to session:" "join-pane -t '%%:'"
bind M command-prompt -p "move window to session:" "move-window -t '%%:'"
