# use alt+tab/alt+maj+tab to move between windows
bind -n M-Tab next-window
bind -n M-BTab previous-window

# ctrl+alt+up/down to move between sessions
bind -n C-M-Up switch-client -p
bind -n C-M-Down switch-client -n

# pane navigation - @is_vim set by nvim autocmds
bind-key -n C-h if-shell -F '#{==:#{@is_vim},on}' "send-keys C-h" "select-pane -L"
bind-key -n C-j if-shell -F '#{==:#{@is_vim},on}' "send-keys C-j" "select-pane -D"
bind-key -n C-k if-shell -F '#{==:#{@is_vim},on}' "send-keys C-k" "select-pane -U"
bind-key -n C-l if-shell -F '#{==:#{@is_vim},on}' "send-keys C-l" "select-pane -R"
bind-key -n C-v copy-mode
bind-key -n C-p paste-buffer

bind ù split-window -v # split pane <prefix>" now bound to <prefix>ù
bind X confirm-before -p "kill-window #W? (y/n)" kill-window # close window now bound to X
bind g display-popup -E -w 80% -h 80% "$SHELL"
bind C command-prompt -p "new session:" "new-session -s '%%'"
bind m command-prompt -p "move pane to session:" "join-pane -t '%%:'"
bind M command-prompt -p "move window to session:" "move-window -t '%%:'"
