set-window-option -g mode-keys vi                # setup copy-mode to work like vim
set -g mouse on
set -g word-separators " "                       # include full word when selecting
set -g base-index 1

set -g status-right-length 100
set -g status-right "#(~/.tmux/plugins/tmux-continuum/scripts/continuum_save.sh)#{S:#{?session_attached,[#{session_name}]* ,[#{session_name}] }}"
