set -g status-left-length 200
run-shell 'tmux set -g status-left "$(~/.config/tmux/status-sessions.sh)"'
set-hook -g client-session-changed 'run-shell "tmux set -g status-left \"$(~/.config/tmux/status-sessions.sh)\""'
set-hook -g session-window-changed 'run-shell "tmux set -g status-left \"$(~/.config/tmux/status-sessions.sh)\""'
set-hook -g window-linked 'run-shell "tmux set -g status-left \"$(~/.config/tmux/status-sessions.sh)\""'
set-hook -g window-unlinked 'run-shell "tmux set -g status-left \"$(~/.config/tmux/status-sessions.sh)\""'
set-hook -g session-renamed 'run-shell "tmux set -g status-left \"$(~/.config/tmux/status-sessions.sh)\""'
set-hook -g after-rename-window 'run-shell "tmux set -g status-left \"$(~/.config/tmux/status-sessions.sh)\""'
set -g window-status-format ""
set -g window-status-current-format ""
set -g status-style "bg=brightblack,fg=brightwhite"
