source-file ~/.config/tmux/options.conf
source-file ~/.config/tmux/status-line.conf
source-file ~/.config/tmux/panes.conf
source-file ~/.config/tmux/bindings.conf
source-file ~/.config/tmux/vim.conf
source-file ~/.config/tmux/bindings-azerty.conf
source-file ~/.config/tmux/autosave.conf
source-file ~/.config/tmux/plugins.conf

source-file -q ~/.config/tmux/local.conf
