# pane navigation - @is_vim set by nvim autocmds
bind-key -n C-h if-shell -F '#{==:#{@is_vim},on}' "send-keys C-h" "select-pane -L"
bind-key -n C-j if-shell -F '#{==:#{@is_vim},on}' "send-keys C-j" "select-pane -D"
bind-key -n C-k if-shell -F '#{==:#{@is_vim},on}' "send-keys C-k" "select-pane -U"
bind-key -n C-l if-shell -F '#{==:#{@is_vim},on}' "send-keys C-l" "select-pane -R"
bind-key -n C-v if-shell -F '#{==:#{@is_vim},on}' "send-keys C-v" "copy-mode"
bind-key -n C-p paste-buffer

# navigate panes from copy-mode while preserving copy-mode in the source pane
bind-key -T copy-mode-vi C-h select-pane -L
bind-key -T copy-mode-vi C-j select-pane -D
bind-key -T copy-mode-vi C-k select-pane -U
bind-key -T copy-mode-vi C-l select-pane -R

# exit copy-mode also with a or i (vim-style "start editing")
bind-key -T copy-mode-vi a send-keys -X cancel
bind-key -T copy-mode-vi i send-keys -X cancel
